schemaVersion: 2.1.0
metadata:
  #section contains metadata about the devfile
  name: albumreview
components:
  #section contains components that will be part of the Che workspace
  - name: albumreview
    container:
      #container config: should we change docker image?
      image: adrianstoica/it1901:latest
      memoryLimit: 3Gi
      endpoints:
        - exposure: public
          name: 6080-tcp-desktop-ui
          protocol: http
          targetPort: 6080
        - exposure: public
          name: 3000-tcp
          protocol: http
          targetPort: 3000
        - exposure: public
          name: 5900-tcp
          protocol: http
          targetPort: 5900
        - exposure: public
          name: 5901-tcp
          protocol: http
          targetPort: 5901
        - exposure: public
          name: 8080-tcp
          protocol: http
          targetPort: 8080
        - exposure: public
          name: 5500-tcp
          protocol: http
          targetPort: 5500
commands:
  - id: changedir
    exec:
      component: albumreview
      commandLine: cd albumreview
      label: change directory
